### ISSUE TITLE
Getting segmentation fault

### ISSUE THREAD

**Issue by rahul3349** [mpromonet/webrtc-streamer#287]
Getting below segmentation fault.
I'm using this project as library and calling APIs in my project.
I've taken all libs listed in cmake list file and html folder to my project, not sure if I missed anything to copy to my project.

[005:262] [11162] (PeerConnectionManager.cpp:931): CreatePeerConnectionCreatePeerConnection peerid:0.1635449345276876
[005:262] [11162] (PeerConnectionManager.h:164): PeerConnectionObserverCreatePeerConnection peerid:0.1635449345276876
[005:281] [11155] (peer_connection_factory.cc:389): Using default network controller factory
[005:281] [11155] (bitrate_prober.cc:69): Bandwidth probing enabled, set to inactive
[New Thread 0x7fffec242700 (LWP 11214)]
[005:281] [11155] (pacing_controller.cc:210): bwe:pacer_updated pacing_kbps=300 padding_budget_kbps=0
[005:281] [11155] (paced_sender.cc:167): ProcessThreadAttached 0x19596b0
[New Thread 0x7fffec141700 (LWP 11215)]
[005:281] [11155] (cpu_info.cc:53): Available number of cores: 8
[005:281] [11155] (aimd_rate_control.cc:107): Using aimd rate control with back off factor 0.85
[005:281] [11155] (remote_bitrate_estimator_single_stream.cc:72): RemoteBitrateEstimatorSingleStream: Instantiating.
[005:281] [11155] (remote_estimator_proxy.cc:50): Maximum interval between transport feedback RTCP messages (ms): 250
[005:282] [11155] (webrtc_session_description_factory.cc:179): DTLS-SRTP enabled; sending DTLS identity request (key type: 1).
[005:282] [11162] (PeerConnectionManager.h:171): PeerConnectionObserverCreateDataChannel peerid:0.1635449345276876
[005:282] [11159] (openssl_identity.cc:43): Making key pair
[005:282] [11155] (peer_connection.cc:6218): Local and Remote descriptions must be applied to get the SSL Role of the SCTP transport.
[005:282] [11155] (PeerConnectionManager.h:223): virtual void PeerConnectionManager::PeerConnectionObserver::OnRenegotiationNeeded() peerid:0.1635449345276876
[005:282] [11159] (openssl_identity.cc:91): Returning key pair
[005:282] [11159] (openssl_certificate.cc:59): Making certificate for WebRTC
[005:282] [11162] (PeerConnectionManager.cpp:632): nbStreams local:0 remote:0 localDescription:0
[005:282] [11162] (webrtc_sdp.cc:3373): Ignored line: a=rtcp:9 IN IP4 0.0.0.0
[005:283] [11162] (webrtc_sdp.cc:3373): Ignored line: a=rtcp:9 IN IP4 0.0.0.0

Thread 2 "pc_network_thre" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeea47700 (LWP 11159)]
0x0000000000000050 in ?? ()
(gdb) bt
#0  0x0000000000000050 in ?? ()
#1  0x00007ffff742cca5 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#2  0x00007ffff742cce6 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#3  0x00007ffff742cde7 in ASN1_item_new () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#4  0x0000000000a53f30 in rtc::OpenSSLCertificate::Generate(rtc::OpenSSLKeyPair*, rtc::SSLIdentityParams const&) ()
#5  0x0000000000a556a2 in rtc::OpenSSLIdentity::GenerateInternal(rtc::SSLIdentityParams const&) ()
#6  0x0000000000a55865 in rtc::OpenSSLIdentity::GenerateWithExpiration(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rtc::KeyParams const&, long) ()
#7  0x000000000075071f in rtc::RTCCertificateGenerator::GenerateCertificate(rtc::KeyParams const&, absl::optional<unsigned long> const&) ()
#8  0x0000000000750a1a in rtc::(anonymous namespace)::RTCCertificateGenerationTask::OnMessage(rtc::Message*) ()
#9  0x0000000000747abb in rtc::MessageQueue::Dispatch(rtc::Message*) ()
#10 0x0000000000758ccc in rtc::Thread::Run() ()
#11 0x00000000007589fd in rtc::Thread::PreRun(void*) ()
#12 0x00007ffff58f86ba in start_thread (arg=0x7fffeea47700) at pthread_create.c:333
#13 0x00007ffff562e41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by rahul3349** [comment]
this crash was related to libcrypto used in my project, I removed this lib linkage and issue solved.
