### ISSUE TITLE
Docker build not working

### ISSUE THREAD

**Issue by Bhlowe** [mpromonet/webrtc-streamer#62]
Looks like a great project. Hope you're still working on it. 

Tried to build:
git clone https://github.com/mpromonet/webrtc-streamer.git
cd webrtc-streamer
sudo docker build .

Here is the output:
`rm -rf alsa-lib-1.1.4.1
make: Leaving directory '/webrtc-streamer'
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /webrtc/src/out/Release/
Command: python -- /webrtc/src/build/config/linux/pkg-config.py -s /webrtc/src/build/linux/debian_jessie_amd64-sysroot -a x64 gmodule-2.0 gtk+-3.0 gthread-2.0
Returned 1.
stderr:

Traceback (most recent call last):
  File "/webrtc/src/build/config/linux/pkg-config.py", line 219, in <module>
    sys.exit(main())
  File "/webrtc/src/build/config/linux/pkg-config.py", line 138, in main
    prefix = GetPkgConfigPrefixToStrip(options, args)
  File "/webrtc/src/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
    "--variable=prefix"] + args, env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //build/config/linux/gtk3/BUILD.gn:15:1: whence it was called.
pkg_config("gtk3_internal_config") {
^-----------------------------------
See //build/config/linux/gtk/BUILD.gn:33:7: which caused the file to be included.
      "//build/config/linux/gtk3",
      ^--------------------------
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends g++ autoconf automake libtool xz-utils         && mkdir /webrtc    && cd /webrtc
        && fetch --no-history --nohooks webrtc  && gclient sync         && make -C /webrtc-streamer live555 alsa-lib    && cd src       && sed -i -e 's|"//webrtc/examples",||' BUILD.gn      && gn gen out/Release --args='is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome" rtc_include_tests=false enable_nacl=false rtc_enable_pr
		`

**Comment by Bhlowe** [comment]
Thanks. That helped.. But now getting compile error:


-I h264bitstream -DVERSION="\"v0.0.5-31-g75c9078-dirty webrtc@98ea2da-dirty live555helper@5d3072a civetweb@v1.9.1-177-gd9b713b h264bitstream@0.2.0\""
In file included from src/PeerConnectionManager.cpp:20:0:
inc/V4l2AlsaMap.h: In function 'std::map<std::basic_string<char>, std::basic_string<char> > getV4l2AlsaMap()':
inc/V4l2AlsaMap.h:39:2: error: 'DIR' was not declared in this scope
  DIR *dp = opendir(video4linuxPath.c_str());
  ^
inc/V4l2AlsaMap.h:39:7: error: 'dp' was not declared in this scope
  DIR *dp = opendir(video4linuxPath.c_str());
       ^
inc/V4l2AlsaMap.h:39:43: error: 'opendir' was not declared in this scope
  DIR *dp = opendir(video4linuxPath.c_str());
                                           ^
inc/V4l2AlsaMap.h:42:28: error: 'readdir' was not declared in this scope
   while((entry = readdir(dp))) {
                            ^
inc/V4l2AlsaMap.h:45:20: error: invalid use of incomplete type 'struct getV4l2AlsaMap()::dirent'
    if (strstr(entry->d_name,"video") == entry->d_name) {
                    ^
inc/V4l2AlsaMap.h:41:10: note: forward declaration of 'struct getV4l2AlsaMap()::dirent'
   struct dirent *entry = NULL;
          ^
inc/V4l2AlsaMap.h:45:46: error: invalid use of incomplete type 'struct getV4l2AlsaMap()::dirent'
    if (strstr(entry->d_name,"video") == entry->d_name) {
                                              ^
inc/V4l2AlsaMap.h:41:10: note: forward declaration of 'struct getV4l2AlsaMap()::dirent'
   struct dirent *entry = NULL;
          ^
inc/V4l2AlsaMap.h:47:40: error: invalid use of incomplete type 'struct getV4l2AlsaMap()::dirent'
     devicePath.append("/").append(entry->d_name).append("/name");
                                        ^
inc/V4l2AlsaMap.h:41:10: note: forward declaration of 'struct getV4l2AlsaMap()::dirent'
   struct dirent *entry = NULL;
          ^
inc/V4l2AlsaMap.h:53:40: error: invalid use of incomplete type 'struct getV4l2AlsaMap()::dirent'
     ueventPath.append("/").append(entry->d_name).append("/device/uevent");
                                        ^
inc/V4l2AlsaMap.h:41:10: note: forward declaration of 'struct getV4l2AlsaMap()::dirent'
   struct dirent *entry = NULL;
          ^
inc/V4l2AlsaMap.h:63:14: error: 'closedir' was not declared in this scope
   closedir(dp);
              ^
In file included from src/PeerConnectionManager.cpp:23:0:
inc/rtspvideocapturer.h: In member function 'virtual bool RTSPAudioSource::onData(const char*, unsigned char*, ssize_t, timeval)':
inc/rtspvideocapturer.h:157:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      while (m_buffer.size() > segmentLength*m_channel) {
                             ^
Makefile:94: recipe for target 'src/PeerConnectionManager.o' failed
make: *** [src/PeerConnectionManager.o] Error 1

**Comment by Bhlowe** [comment]
And the gtk3 error is back. :(

make[1]: Leaving directory '/webrtc-streamer/live'
rm -rf live
make: Leaving directory '/webrtc-streamer'
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /webrtc/src/out/Release/
Command: python -- /webrtc/src/build/config/linux/pkg-config.py -s /webrtc/src/build/linux/debian_stretch_amd64-sysroot -a x64 gmodule-2.0 gtk+-3.0 gthread-2.0
Returned 1.
stderr:

Traceback (most recent call last):
  File "/webrtc/src/build/config/linux/pkg-config.py", line 232, in <module>
    sys.exit(main())
  File "/webrtc/src/build/config/linux/pkg-config.py", line 139, in main
    prefix = GetPkgConfigPrefixToStrip(options, args)
  File "/webrtc/src/build/config/linux/pkg-config.py", line 80, in GetPkgConfigPrefixToStrip
    "--variable=prefix"] + args, env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //build/config/linux/gtk3/BUILD.gn:15:1: whence it was called.
pkg_config("gtk3_internal_config") {
^-----------------------------------
See //build/config/linux/gtk/BUILD.gn:33:7: which caused the file to be included.
      "//build/config/linux/gtk3",
      ^--------------------------
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends g++ autoconf automake libtool xz-utils libasound-dev         && mkdir /webrtc      && cd /webrtc   && fetch --no-history --nohooks webrtc  && sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS         && gclient sync         && make -C /webrtc-streamer live555     && cd src       && sed -i -e 's|"examples",||' BUILD.gn         && gn gen out/Release --args='is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome" rtc_include_tests=false rtc_enable_protobuf=false use_custom_libcxx=false use_ozone=true rtc_include_pulse_audio=false'      && ninja -C out/Release jsoncpp rtc_json webrtc         && cd /webrtc-streamer  && make all' returned a non-zero code: 1
